name: Run Main

on: push

jobs:
  run-main:
    name: Run Main
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      
      - name: Setup V
        uses: vlang/setup-v@v1.1
      
      - name: Setup ZeroMQ
        run: sudo apt-get install -y libzmq3-dev libczmq-dev
      
      - name: Compile and run main.v
        run: v run main.v
