name: Run Tests

on: push

jobs:
  run-main:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Setup V
        uses: vlang/setup-v@v1.1

      - name: Update packages
        run: sudo apt-get update

      - name: Setup ZeroMQ
        run: sudo apt-get install -y --no-install-recommends libzmq3-dev libczmq-dev

      - name: Run tests
        run: v -stats test src/vmq_test.v
